issues:
  exclude-files:
    - "mock.*\\.go"
  exclude-rules:
    - path: '.+_test\.go'
      linters:
        - forcetypeassert
output:
  print-issued-lines: false
linters:
  enable-all: false
  disable-all: true
  fast: false
  enable:
    - errchkjson
    - errorlint
    - godot
    - goerr113
    - gofumpt
    - intrange
    - ireturn
    - lll
    - nestif
    - nilerr
    - nlreturn
    - revive
    - testifylint
    - wrapcheck
    - wsl
