style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/kilianc/pretender
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - chore
  commit_groups:
    group_by: Type
    sort_by: Title
    title_order:
      - fix
      - feat
      - chore
    title_maps:
      feat: ✨
      fix: 🐛
      chore: 🧹
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
