name: docker

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (e.g., v1.2.3)'
        required: true

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            kilianciuffolo/pretender
          tags: |
            type=ref,event=tag
            type=semver,pattern=v{{version}},value=${{ github.event.inputs.tag || github.ref }}
            type=semver,pattern=v{{major}}.{{minor}},value=${{ github.event.inputs.tag || github.ref }}
            type=semver,pattern=v{{major}},value=${{ github.event.inputs.tag || github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64, linux/arm64
